version: "3.8"
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=anka_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  mysql_data:
  redis_data:
